### ISSUE TITLE
Can't get bounds-checking to work

### ISSUE THREAD

**Issue by rab** [rab/pixie#1]
OK, @gigasquid here's my problem. The `throw` seems to not want to play nicely with the normal code. It's almost like `if` and `when` don't quite act like special forms and evaluate their arguments.

```
./pixie-vm run-tests.pxi pixie.tests.test-ith
```

If you pull this branch (I've made you a collaborator, too), you can run just the `ith` tests with the above. Note that the tests that expect failure (i.e., to `catch` the OOB that `ith` will `throw`) have been commented out.

I don't know if today is a work-holiday for you, but it is for my client. I was planning to work on taxes today, but can break for another go at this if you're free.

**Comment by gigasquid** [comment]
After digging - I found the cause was that `and` wasn't working right.  This was because we defined our function using it _before_ the and macro was defined.  I moved the function and it works much better now :)

**Comment by gigasquid** [comment]
I went ahead and sent a pull request https://github.com/pixie-lang/pixie/pull/187
